<?PHP
/*********************************************************************************
 * SugarCRM Community Edition is a customer relationship management program developed by
 * SugarCRM, Inc. Copyright (C) 2004-2013 SugarCRM Inc.
 * 
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Affero General Public License version 3 as published by the
 * Free Software Foundation with the addition of the following permission added
 * to Section 15 as permitted in Section 7(a): FOR ANY PART OF THE COVERED WORK
 * IN WHICH THE COPYRIGHT IS OWNED BY SUGARCRM, SUGARCRM DISCLAIMS THE WARRANTY
 * OF NON INFRINGEMENT OF THIRD PARTY RIGHTS.
 * 
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more
 * details.
 * 
 * You should have received a copy of the GNU Affero General Public License along with
 * this program; if not, see http://www.gnu.org/licenses or write to the Free
 * Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
 * 02110-1301 USA.
 * 
 * You can contact SugarCRM, Inc. headquarters at 10050 North Wolfe Road,
 * SW2-130, Cupertino, CA 95014, USA. or at email address contact@sugarcrm.com.
 * 
 * The interactive user interfaces in modified source and object code versions
 * of this program must display Appropriate Legal Notices, as required under
 * Section 5 of the GNU Affero General Public License version 3.
 * 
 * In accordance with Section 7(b) of the GNU Affero General Public License version 3,
 * these Appropriate Legal Notices must retain the display of the "Powered by
 * SugarCRM" logo. If the display of the logo is not reasonably feasible for
 * technical reasons, the Appropriate Legal Notices must display the words
 * "Powered by SugarCRM".
 ********************************************************************************/

/**
 * THIS CLASS IS GENERATED BY MODULE BUILDER
 * PLEASE DO NOT CHANGE THIS CLASS
 * PLACE ANY CUSTOMIZATIONS IN lxm1_lxm_residents1
 */


class lxm1_lxm_residents1_sugar extends Basic {
	var $new_schema = true;
	var $module_dir = 'lxm1_lxm_residents1';
	var $object_name = 'lxm1_lxm_residents1';
	var $table_name = 'lxm1_lxm_residents1';
	var $importable = false;
	var $disable_row_level_security = true ; // to ensure that modules created and deployed under CE will continue to function under team security if the instance is upgraded to PRO
		var $id;
		var $name;
		var $date_entered;
		var $date_modified;
		var $modified_user_id;
		var $modified_by_name;
		var $created_by;
		var $created_by_name;
		var $description;
		var $deleted;
		var $created_by_link;
		var $modified_user_link;
		var $assigned_user_id;
		var $assigned_user_name;
		var $assigned_user_link;
		var $gender_c;
		var $marital_situation;
		var $residences_address;
		var $persent_address;
		var $work_unit;
		var $phone;
		var $personal_details;
		var $pocketbook;
		var $disease_situation;
		var $primary_issue;
		var $issue_type;
		var $event_place;
		var $start_date;
		var $aggressive_behavior;
		var $handle_unit;
		var $has_paper_advice;
		var $reply_time;
		var $has_litigation_process;
		var $has_hearing_process;
		var $has_leader_contacted;
		var $leader_name;
		var $leader_unit;
		var $leader_position;
		var $has_solution;
		var $handle_status;
		var $residents_situation;
		var $responsibility_unit;
		var $responsibility_people;
		var $responsibility_position;
		var $responsibility_phone;
		var $isdraft;
		var $birthday;
		var $belong_street;
		var $nationality;
		var $ethnic_groups;
		var $has_double_check_process;
		var $numbers_up;
		var $id_number;
		function lxm1_lxm_residents1_sugar(){	
		parent::Basic();
	}
	
	function bean_implements($interface){
		switch($interface){
			case 'ACL': return true;
		}
		return false;
}
		
}
?>